name: Cypress Tests + Publish Report

on:
  push:
    branches: [ main ]
 
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: cypress_cucumber/package-lock.json

      - name: Clean old reports
        run: rm -rf cypress/cucumber-json cypress/cucumber-htmlreport
        working-directory: cypress_cucumber

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: cypress_cucumber
          browser: chrome

      - name: Upload screenshots on test failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: cypress_cucumber/cypress/screenshots

      - name: Upload videos on test failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: videos
          path: cypress_cucumber/cypress/videos

      - name: Generate HTML report of test results
        run: node generate-report.js
        working-directory: cypress_cucumber

      #  Upload report as GitHub Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: cypress_cucumber/cypress/cucumber-htmlreport

      # Deploy report to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
